export const APPS = [
  {
    id: "roomly",
    name: "Roomly",
    tag: "Flagship",
    tagline: "Roommate Management",
    desc: "Split expenses, manage chores, and keep shared living organized — built for real roommates.",
    color: "#3B82F6",
    features: ["Smart expense splitting", "Shared task boards", "Bill reminders"],
    stat: "2,400+ households",
    live: true,
    angle: 0,
  },
  {
    id: "tokitaki",
    name: "TokiTaki",
    tag: "Live",
    tagline: "Expense Tracker",
    desc: "AI-powered budgeting that auto-categorizes spending and keeps your finances crystal clear.",
    color: "#8B5CF6",
    features: ["AI categorization", "Visual budgets", "Spending forecasts"],
    stat: "1,800+ users",
    live: true,
    angle: 90,
  },
  {
    id: "dmv",
    name: "DMV Practice",
    tag: "Beta",
    tagline: "DMV Test Prep",
    desc: "Ace your California DMV written test with 500+ real questions and adaptive learning.",
    color: "#06B6D4",
    features: ["500+ questions", "Adaptive learning", "Offline mode"],
    stat: "In development",
    live: false,
    angle: 180,
  },
  {
    id: "ai",
    name: "AI Suite",
    tag: "Soon",
    tagline: "Productivity Platform",
    desc: "Write, summarize, and automate workflows in one unified AI workspace.",
    color: "#10B981",
    features: ["Writing assistant", "Doc summarizer", "Automation"],
    stat: "Launching Q3 2025",
    live: false,
    angle: 270,
  },
] as const;

export const SERVICES = [
  { id: "ai", label: "AI Solutions", desc: "Intelligent systems that learn and adapt", color: "#8B5CF6" },
  { id: "web", label: "Web Apps", desc: "Fast, beautiful web experiences", color: "#3B82F6" },
  { id: "mobile", label: "Mobile Apps", desc: "Native-feel iOS & Android apps", color: "#06B6D4" },
  { id: "auto", label: "Automation", desc: "Workflows that run while you sleep", color: "#10B981" },
  { id: "ext", label: "Extensions", desc: "Browser tools that feel invisible", color: "#F59E0B" },
  { id: "custom", label: "Custom Software", desc: "Bespoke products from scratch", color: "#F472B6" },
] as const;

export const STATS = [
  { value: 5, suffix: "+", label: "Products launched" },
  { value: 4200, suffix: "+", label: "Active users" },
  { value: 98, suffix: "%", label: "Satisfaction" },
] as const;
